### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by Bradley-Karat** [Bradley-Karat/DiffSimGen#2]
List of tasks to-do:

- **Add in new models (DMIPY)**:
    - [ ] Ball and sticks (two and three)
    - [ ] Cylinder
    - [ ] Ball and racket
    - [ ] NODDI-Bingham
    - [ ] Multi-tissue NODDI (assumes different S0 for each compartment)
    - [ ] AxCaliber
    - [ ] IVIM
    - [ ] VERDICT
- **Add in new models (DIPY)**:
    - [ ] DTI
    - [ ] DKI
- [ ] **Add in another jupyter notebook linking uGUIDE and DiffSimGen**:
    - i.e. what to do with your simulated data
- [ ] **Attempt to learn and inject realistic noise into simulated signal from real data with GAN**:
    - First fit NLLS to data to get realistic parameter distribution
    - Simulate ground-truth signal with the above parameters (no noise)
    - Train GAN to discriminate between real noisy signal and noiseless simulated signal (the generators job is to inject noise to make noiseless signal look like real signal)
    - Compare the GAN outputs to standard ways of injecting noise (SNR, noisemaps from dwidenoise, etc...)
- [ ] **Build a toolbox for supervised model fitting based on data simulated from DiffSimGen**:
